export const TEXTURE_ASSET = {
  // Tiles
  hole: {
    name: 'hole',
    path: 'assets/tiles/',
    ext: '.png',
    texture: null,
  },
  edge: {
    name: 'edge',
    path: 'assets/tiles/',
    ext: '.png',
    texture: null,
  },
  ground: {
    name: 'ground',
    path: 'assets/tiles/',
    ext: '.png',
    texture: null,
  },
  n: {
    name: 'n',
    path: 'assets/tiles/',
    ext: '.png',
    texture: null,
  },
  s: {
    name: 's',
    path: 'assets/tiles/',
    ext: '.png',
    texture: null,
  },
  e: {
    name: 'e',
    path: 'assets/tiles/',
    ext: '.png',
    texture: null,
  },
  w: {
    name: 'w',
    path: 'assets/tiles/',
    ext: '.png',
    texture: null,
  },
  ne: {
    name: 'ne',
    path: 'assets/tiles/',
    ext: '.png',
    texture: null,
  },
  nw: {
    name: 'nw',
    path: 'assets/tiles/',
    ext: '.png',
    texture: null,
  },
  w_e: {
    name: 'w_e',
    path: 'assets/tiles/',
    ext: '.png',
    texture: null,
  },
  n_nw_w: {
    name: 'n_nw_w',
    path: 'assets/tiles/',
    ext: '.png',
    texture: null,
  },
  n_ne_e: {
    name: 'n_ne_e',
    path: 'assets/tiles/',
    ext: '.png',
    texture: null,
  },
  all: {
    name: 'all',
    path: 'assets/tiles/',
    ext: '.png',
    texture: null,
  },
  // Props
  bone: {
    name: 'bone',
    path: 'assets/props/',
    ext: '.png',
    texture: null,
  },
  crate_silver: {
    name: 'crate_silver',
    path: 'assets/props/',
    ext: '.png',
    texture: null,
  },
  crate_wood: {
    name: 'crate_wood',
    path: 'assets/props/',
    ext: '.png',
    texture: null,
  },
  flag: {
    name: 'flag',
    path: 'assets/props/',
    ext: '.png',
    texture: null,
  },
  handcuff_1: {
    name: 'handcuff_1',
    path: 'assets/props/',
    ext: '.png',
    texture: null,
  },
  handcuff_2: {
    name: 'handcuff_2',
    path: 'assets/props/',
    ext: '.png',
    texture: null,
  },
  health_large: {
    name: 'health_large',
    path: 'assets/props/',
    ext: '.png',
    texture: null,
  },
  health_small: {
    name: 'health_small',
    path: 'assets/props/',
    ext: '.png',
    texture: null,
  },
  key_gold: {
    name: 'key_gold',
    path: 'assets/props/',
    ext: '.png',
    texture: null,
  },
  key_silver: {
    name: 'key_silver',
    path: 'assets/props/',
    ext: '.png',
    texture: null,
  },
  ladder: {
    name: 'ladder',
    path: 'assets/props/',
    ext: '.png',
    texture: null,
  },
  lamp: {
    name: 'lamp',
    path: 'assets/props/',
    ext: '.png',
    texture: null,
  },
  mana_large: {
    name: 'mana_large',
    path: 'assets/props/',
    ext: '.png',
    texture: null,
  },
  mana_small: {
    name: 'mana_small',
    path: 'assets/props/',
    ext: '.png',
    texture: null,
  },
  peak: {
    name: 'peak',
    path: 'assets/props/',
    ext: '.png',
    texture: null,
  },
  skull: {
    name: 'skull',
    path: 'assets/props/',
    ext: '.png',
    texture: null,
  },
  stones_large: {
    name: 'stones_large',
    path: 'assets/props/',
    ext: '.png',
    texture: null,
  },
  stones_small: {
    name: 'stones_small',
    path: 'assets/props/',
    ext: '.png',
    texture: null,
  },
  torch: {
    name: 'torch',
    path: 'assets/props/',
    ext: '.png',
    texture: null,
  },
  web_left: {
    name: 'web_left',
    path: 'assets/props/',
    ext: '.png',
    texture: null,
  },
  web_right: {
    name: 'web_right',
    path: 'assets/props/',
    ext: '.png',
    texture: null,
  },
  // Monsters
  bandit: {
    name: 'bandit',
    path: 'assets/monsters/',
    ext: '.png',
    texture: null,
  },
  centaur_female: {
    name: 'centaur_female',
    path: 'assets/monsters/',
    ext: '.png',
    texture: null,
  },
  centaur_male: {
    name: 'centaur_male',
    path: 'assets/monsters/',
    ext: '.png',
    texture: null,
  },
  mushroom_large: {
    name: 'mushroom_large',
    path: 'assets/monsters/',
    ext: '.png',
    texture: null,
  },
  mushroom_small: {
    name: 'mushroom_small',
    path: 'assets/monsters/',
    ext: '.png',
    texture: null,
  },
  skeleton: {
    name: 'skeleton',
    path: 'assets/monsters/',
    ext: '.png',
    texture: null,
  },
  troll: {
    name: 'troll',
    path: 'assets/monsters/',
    ext: '.png',
    texture: null,
  },
  wolf: {
    name: 'wolf',
    path: 'assets/monsters/',
    ext: '.png',
    texture: null,
  },
};
